"""
services/session_service.py

Orchestrates session lifecycle, student submission flow, and concept gap computation.
All persistence delegated to database.py.
All scoring delegated to scoring_service.py → hybrid_engine.
"""

import random
import string
from datetime import datetime

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import config
import database
from services.scoring_service import score_response


# ── Session Code Generation ───────────────────────────────────────────────────

def _random_code(length: int = 6) -> str:
    chars = string.ascii_uppercase + string.digits
    return "".join(random.choices(chars, k=length))


def generate_session_code() -> str:
    """
    Generate a unique 6-character alphanumeric session code.
    Loops until a code not already in the database is found.
    """
    while True:
        code = _random_code()
        if not database.session_exists(code):
            return code


# ── Session CRUD ──────────────────────────────────────────────────────────────

def create_session(
    teacher_id: str,
    topic: str,
    question: str,
    threshold: int = 75,
) -> str:
    """Create a new session and return its session code."""
    code = generate_session_code()
    now  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    database.create_session(code, teacher_id, topic, question, threshold, now)
    return code


def get_session(session_code: str) -> dict | None:
    return database.get_session(session_code)


def close_session(session_code: str) -> None:
    database.deactivate_session(session_code)


def get_teacher_sessions(teacher_id: str) -> list[dict]:
    return database.get_teacher_sessions(teacher_id)


def check_plagiarism_and_verify(new_response: str, question: str, topic: str, previous_responses: list[str]) -> dict:
    """Uses Groq to check plagiarism, AI generation, and conceptual correctness in one call."""
    if not new_response or getattr(config, "groq_client", None) is None:
        return {"flag": None, "ai_score": None, "feedback": None}
        
    has_previous = len(previous_responses) > 0
    
    prompt = (
        f"Topic: '{topic}'\n"
        f"Question: '{question}'\n"
        f"Student Answer: '{new_response}'\n"
    )
    if has_previous:
        prompt += "\nPrevious Student Answers:\n"
        for i, ans in enumerate(previous_responses):
            prompt += f"[{i+1}]: '{ans}'\n"
        
    prompt += (
        "\nTask: Evaluate the Student Answer based on the following checks:\n"
        "1. PLAGIARISM: Is it a copy of the Question or any of the Previous Student Answers?\n"
        "2. AI DETECTION: Is it likely generated by an AI (ChatGPT/Claude)?\n"
        "3. CONCEPTUAL CHECK: Regardless of exact keywords, is the answer conceptually correct and sufficiently deep for this topic?\n"
        "\nRules:\n"
        "- If the student answer is merely a copy, a rephrase, or a 'version-in-question' of the original Question, YOU MUST flag as 'Mimics Question' and set 'plagiarism_score' to 100. Be extremely suspicious of answers that are very similar in structure to the question.\n"
        "- If it copies a previous answer, flag as 'Highly Similar to Previous Answer' and set 'plagiarism_score' to 100.\n"
        "- If the text is clearly generated by an AI (e.g., includes 'As an AI language model', follows a formulaic structure, or is overly clean/formal), YOU MUST flag as 'Likely AI Generated' and set 'plagiarism_score' to 100.\n"
        "- Provide a 'Plagiarism Score' (0-100) representing the probability (percentage) of plagiarism or AI-usage.\n"
        "- Provide a 'Conceptual Score' from 0 to 100. If the answer is just the question, the score MUST be 0.\n"
        "- Provide 'missing_concepts': A short list (max 3) of specific sub-topics or logical bridges the student missed.\n"
        "- Provide 'study_tip': A 1-sentence supportive tip specifically for THIS student's answer.\n"
        "\nOutput ONLY a JSON object with keys: 'flag' (string or null), 'plagiarism_score' (integer 0-100), 'conceptual_score' (integer 0-100), 'reason' (string), 'missing_concepts' (array), 'study_tip' (string)."
    )

    try:
        chat_completion = config.groq_client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a professional pedagogical grader. You MUST identify AI-generated text. Return only JSON."},
                {"role": "user", "content": prompt}
            ],
            model="llama-3.1-8b-instant",
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        import json
        content = chat_completion.choices[0].message.content
        res = json.loads(content)
        
        # Safety: If flag is set, ensure score matches its importance
        flag = res.get("flag")
        p_score = res.get("plagiarism_score", 0)
        if flag == "Likely AI Generated" and p_score < 90:
            p_score = 100  # Categorical for AI
        elif flag and p_score == 0:
            p_score = 85
            
        return {
            "flag": flag,
            "plagiarism_rate": p_score,
            "ai_score": res.get("conceptual_score", 0),
            "feedback": res.get("reason"),
            "missing_concepts": res.get("missing_concepts", []),
            "study_tip": res.get("study_tip", "")
        }
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"Groq verification failed: {e}")
    return {"flag": None, "ai_score": None, "feedback": None}

# ── Student Submission Flow ───────────────────────────────────────────────────

def submit_student_response(
    session_code: str,
    student_name: str,
    response: str,
    topic: str = "",
    threshold: int = 75,
) -> tuple[bool, str, float, str, str, str]:
    """
    Score the student's response and persist it.
    Also recomputes concept gap coverage for the session after insertion.

    Returns:
        (success, message, score, status, reason_text, missing_keywords_text)
    """
    # --- 1. Base Logic (Keywords) ---
    score, status, reason_text, missing_keywords = score_response(
        response, topic=topic, threshold=threshold
    )

    session_info = get_session(session_code)
    question = session_info["question"] if session_info else "concept question"
    previous_submissions = get_submissions(session_code)
    prev_responses = [sub["response"] for sub in previous_submissions]

    # --- 2. Mimicry check (Fuzzy local) ---
    def _sanitize(t): return "".join(c for c in t if c.isalnum()).lower()
    if _sanitize(response) == _sanitize(question):
        plag_flag = "Mimics Question"
        plag_rate = 100
        ai_score = 0
        ai_feedback = "Exact or punctuation-only copy of question detected."
        ai_check = {"missing_concepts": [], "study_tip": "Do not copy the question. Use your own words."}
    else:
        # --- 3. AI Verification (Groq) ---
        ai_check = check_plagiarism_and_verify(response, question, topic, prev_responses)
        plag_flag = ai_check["flag"]
        plag_rate = ai_check["plagiarism_rate"]
        ai_score = ai_check["ai_score"]
        ai_feedback = ai_check["feedback"]

    # --- 4. Hybrid Logic: Overrides & Upgrades ---
    if ai_score is not None:
        if ai_score >= 95:
            status = "Engaged"
            score  = max(score, float(ai_score))
            reason_text += f" | AI Content Verified (Accuracy: {ai_score}%): {ai_feedback}"
        elif ai_score >= 80 and status == "Disengaged":
            status = "Partially Engaged"
            score  = max(score, float(ai_score))
            reason_text += f" | AI Content Verified (Accuracy: {ai_score}%): {ai_feedback}"

    if plag_flag:
        reason_text += f" | Source: {plag_flag} (Risk: {plag_rate}%)"
        if plag_flag in ["Mimics Question", "Highly Similar To Previous Answer"]:
            status = "Disengaged"
            score  = 0.0
            reason_text += " | CRITICAL: Submission invalidated due to mimicry/copying."
    else:
        reason_text += " | Source: Original"

    # --- 5. AI-Driven Student Tips & Gaps ---
    ai_tip = ai_check.get("study_tip", "")
    if ai_tip:
        reason_text += f" | TIP: {ai_tip}"
        
    ai_gaps = ai_check.get("missing_concepts", [])
    if ai_gaps:
        ai_gap_text = " | ".join(ai_gaps)
        missing_keywords = f"{missing_keywords} | {ai_gap_text}".strip(" |")

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    success, message = database.insert_submission(
        session_code, student_name, response,
        score, status, reason_text, missing_keywords, now,
        plagiarism_rate=float(plag_rate)
    )

    if success:
        _compute_and_store_concept_gaps(session_code, topic)

    return success, message, score, status, reason_text, missing_keywords


def _compute_and_store_concept_gaps(session_code: str, topic: str) -> None:
    """
    Aggregate keyword coverage across all submissions for this session
    and persist Gap_Index values to the concept_coverage table.

    Gap_Index(k) = 1 - Coverage_ratio(k)
    Coverage_ratio(k) = (students whose response contains keyword k) / total_students
    """
    submissions = database.get_submissions(session_code)
    total = len(submissions)
    if total == 0:
        return

    clusters = config.get_topic_clusters(topic)
    if not clusters:
        return   # unknown topic — no keyword gap analysis possible

    response_texts = [s["response"].lower() for s in submissions]

    for cluster_name, keywords in clusters:
        for keyword in keywords:
            hits           = sum(1 for rt in response_texts if keyword in rt)
            coverage_ratio = hits / total
            gap_index      = 1.0 - coverage_ratio
            flagged        = 1 if gap_index > config.GAP_THRESHOLD else 0

            database.upsert_concept_coverage(
                session_code, keyword, cluster_name,
                round(coverage_ratio, 4), round(gap_index, 4), flagged,
            )


# ── Analytics Helpers ─────────────────────────────────────────────────────────

def get_submissions(session_code: str) -> list[dict]:
    return database.get_submissions(session_code)


def get_session_summary(session_code: str) -> dict:
    """Returns engagement counts + class mean/std Understanding Score."""
    return database.get_session_summary(session_code)


def get_concept_gaps(session_code: str) -> list[dict]:
    """Return concept coverage records sorted by gap_index descending."""
    return database.get_concept_gaps(session_code)


def get_topic_progression(teacher_id: str, topic: str) -> list[dict]:
    """Multi-session mean scores for the line chart."""
    return database.get_topic_progression(teacher_id, topic)


def generate_session_inference(session_code: str) -> str:
    """Aggregates session data and generates an AI summary/inference via Groq."""
    session = get_session(session_code)
    if not session or getattr(config, "groq_client", None) is None:
        return "Inference unavailable."

    submissions = get_submissions(session_code)
    if not submissions:
        return "No submissions to analyze."

    topic = session["topic"]
    question = session["question"]
    
    # Prep data for AI
    results_summary = ""
    for s in submissions:
        results_summary += f"- Student: {s['student_name']}, Score: {s['score']}%, Status: {s['status']}, Reason: {s['reason']}\n"

    prompt = (
        f"Topic: {topic}\n"
        f"Question asked: {question}\n\n"
        f"Student Performance Data:\n{results_summary}\n"
        "Task: Based on these results, provide a concise pedagogical inference for the teacher.\n"
        "1. Identify common conceptual gaps or patterns in mistakes.\n"
        "2. Suggest an alternate teaching method, analogy, or mental model that would help students master this specific topic better.\n"
        "3. Tone: Be highly supportive, professional, and collaborative. Do NOT criticize or undermine the teacher's current method; instead, offer the suggestion as a supplemental or 'next step' strategy.\n"
        "4. Format: Use Markdown. Start with a header '### 💡 Session Insights' followed by '#### Analysis' and '#### Teaching Suggestion'."
    )

    try:
        chat_completion = config.groq_client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are an expert pedagogical advisor and mentor for computer science teachers. Your goal is to improve student outcomes through supportive, data-driven feedback."},
                {"role": "user", "content": prompt}
            ],
            model="llama-3.1-8b-instant",
            temperature=0.7,
            max_completion_tokens=400,
        )
        inference_text = chat_completion.choices[0].message.content.strip()
        database.update_session_inference(session_code, inference_text)
        return inference_text
    except Exception as e:
        print(f"Groq inference generation failed: {e}")
        return "Failed to generate AI inference due to an API error."
